name = "em-c-proposals"
compatibility_date = "2025-09-10"
compatibility_flags = ["nodejs_als", "nodejs_compat"]
preview_urls = true
account_id = "SvWdThM_N2JTyYqgmnemJRMv4nOytpNrw9l2bIWD"

[assets]
directory = ".svelte-kit/cloudflare"
not_found_handling = "404-page"
binding = "ASSETS"

observability = {
    "enabled": true
}

[vars]
IS_DEV = "false"
TEMPLATE = "https://em-c-proposals.pages.dev/templates/ccbTemplate.pdf"
PROPOSAL_FORM_TEST = false
CLOUDFLARE_API_TOKEN = "SvWdThM_N2JTyYqgmnemJRMv4nOytpNrw9l2bIWD"

[[d1_databases]]
binding = "DB"
database_name = "emc_planning",
database_id = "ca3bc565-e262-4e3a-8d0a-c3d523022e0e"
experimental_remote = true

[[secrets_store]]
binding = "SECRET"
secret_name = "emc_db_secret"